// ===== items.js =====
const SHOP_ITEMS = {
  weapon: [
    // ── EVIL ──
    {
      id:         'snp_evil',
      name:       'SNP EVIL',
      icon:       '<img src="assets/items/snp_evil.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => 0,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/snp_evil.png' },
      weaponId:   'snp_evil',
    },
    {
      id:         'asr_evil',
      name:       'ASR EVIL',
      icon:       '<img src="assets/items/asr_evil.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => 0,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/asr_evil.png' },
      weaponId:   'asr_evil',
    },
    // ── PPAP ──
    {
      id:         'snp_ppap',
      name:       'SNP PPAP',
      icon:       '<img src="assets/items/snp_ppap.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_SNP_PPAP,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/snp_ppap.png' },
      weaponId:   'snp_ppap',
    },
    // ── PIGGY ──
    {
      id:         'snp_piggy',
      name:       'SNP PIGGY',
      icon:       '<img src="assets/items/snp_piggy.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => 0,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/snp_piggy.png' },
      weaponId:   'snp_piggy',
    },
    {
      id:         'asr_piggy',
      name:       'ASR PIGGY',
      icon:       '<img src="assets/items/asr_piggy.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => 0,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/asr_piggy.png' },
      weaponId:   'asr_piggy',
    },
  ],
  knife: [],
  armor: [
    // ── EVIL ──
    {
      id:         'body_evil',
      name:       'BODY EVIL',
      icon:       '<img src="assets/items/body_evil.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => 0,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'armor', img: 'assets/items/body_evil.png' },
      armorId:    'body_evil',
    },
    // ── PPAP ──
    {
      id:         'body_ppap',
      name:       'BODY PPAP',
      icon:       '<img src="assets/items/body_ppap.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_BODY_PPAP,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'armor', img: 'assets/items/body_ppap.png' },
      armorId:    'body_ppap',
      armor:      78,
    },
    // ── PIGGY ──
    {
      id:         'body_piggy',
      name:       'BODY PIGGY',
      icon:       '<img src="assets/items/body_piggy.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => 0,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'armor', img: 'assets/items/body_piggy.png' },
      armorId:    'body_piggy',
      armor:      75,
    },
  ],
  helmet: [
    // ── EVIL ──
    {
      id:         'head_evil',
      name:       'HEAD EVIL',
      icon:       '<img src="assets/items/head_evil.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => 0,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'helmet', img: 'assets/items/head_evil.png' },
      armorId:    'head_evil',
    },
    // ── PPAP ──
    {
      id:         'head_ppap',
      name:       'HEAD PPAP',
      icon:       '<img src="assets/items/head_ppap.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_HEAD_PPAP,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'helmet', img: 'assets/items/head_ppap.png' },
      armorId:    'head_ppap',
      armor:      79,
    },
    // ── PIGGY ──
    {
      id:         'head_piggy',
      name:       'HEAD PIGGY',
      icon:       '<img src="assets/items/head_piggy.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => 0,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'helmet', img: 'assets/items/head_piggy.png' },
      armorId:    'head_piggy',
      armor:      76,
    },
  ],
  med: [
    {
      id:         'bandage',
      name:       'BANDAGE',
      icon:       '<img src="assets/items/bandage.png" style="width:32px;height:auto;object-fit:contain;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_BANDAGE ?? 50,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'med' },
      heal:       100,
    },
  ],
  supply: [
    {
      id:         'ammo_box',
      name:       'AMMO BOX',
      icon:       '📦',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_AMMO_BOX,
      consumable: true,
      noStackBP:  false,
      equip:      null,
    },
  ],
};
