// ===== items.js =====
const SHOP_ITEMS = {
  weapon: [
    // ── RED DEVIL ──
    {
      id:         'asr_reddevil',
      name:       'ASR RED DEVIL',
      icon:       '<img src="assets/items/asr_reddevil.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_ASR_REDDEVIL,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/asr_reddevil.png' },
      weaponId:   'asr_reddevil',
    },
    {
      id:         'snp_reddevil',
      name:       'SNP RED DEVIL',
      icon:       '<img src="assets/items/snp_reddevil.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_SNP_REDDEVIL,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/snp_reddevil.png' },
      weaponId:   'snp_reddevil',
    },
    // ── PPAP ──
    {
      id:         'snp_ppap',
      name:       'SNP PPAP',
      icon:       '<img src="assets/items/snp_ppap.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_SNP_PPAP,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/snp_ppap.png' },
      weaponId:   'snp_ppap',
    },
    // ── BLUE ACT ──
    {
      id:         'asr_blueact',
      name:       'ASR BLUE ACT',
      icon:       '<img src="assets/items/asr_blueact.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_ASR_BLUEACT,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/asr_blueact.png' },
      weaponId:   'asr_blueact',
    },
    {
      id:         'snp_blueact',
      name:       'SNP BLUE ACT',
      icon:       '<img src="assets/items/snp_blueact.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_SNP_BLUEACT,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/snp_blueact.png' },
      weaponId:   'snp_blueact',
    },
    // ── CHICAGO ──
    {
      id:         'asr_chicago',
      name:       'ASR CHICAGO',
      icon:       '<img src="assets/items/asr_chicago.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_ASR_CHICAGO,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/asr_chicago.png' },
      weaponId:   'asr_chicago',
    },
    {
      id:         'snp_chicago',
      name:       'SNP CHICAGO',
      icon:       '<img src="assets/items/snp_chicago.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_SNP_CHICAGO,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/snp_chicago.png' },
      weaponId:   'snp_chicago',
    },
    // ── EVIL ──
    {
      id:         'asr_evil',
      name:       'ASR EVIL',
      icon:       '<img src="assets/items/asr_evil.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_ASR_EVIL,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/asr_evil.png' },
      weaponId:   'asr_evil',
    },
    {
      id:         'snp_evil',
      name:       'SNP EVIL',
      icon:       '<img src="assets/items/snp_evil.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_SNP_EVIL,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/snp_evil.png' },
      weaponId:   'snp_evil',
    },
    // ── LUCIFER ──
    {
      id:         'asr_lucifer',
      name:       'ASR LUCIFER',
      icon:       '<img src="assets/items/asr_lucifer.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_ASR_LUCIFER,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/asr_lucifer.png' },
      weaponId:   'asr_lucifer',
    },
    {
      id:         'snp_lucifer',
      name:       'SNP LUCIFER',
      icon:       '<img src="assets/items/snp_lucifer.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_SNP_LUCIFER,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/snp_lucifer.png' },
      weaponId:   'snp_lucifer',
    },
    // ── PIGGY ──
    {
      id:         'asr_piggy',
      name:       'ASR PIGGY',
      icon:       '<img src="assets/items/asr_piggy.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_ASR_PIGGY,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/asr_piggy.png' },
      weaponId:   'asr_piggy',
    },
    {
      id:         'snp_piggy',
      name:       'SNP PIGGY',
      icon:       '<img src="assets/items/snp_piggy.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_SNP_PIGGY,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'weapon', img: 'assets/items/snp_piggy.png' },
      weaponId:   'snp_piggy',
    },
  ],
  knife: [],
  armor: [
    // ── RED DEVIL ──
    {
      id:         'body_reddevil',
      name:       'BODY RED DEVIL',
      icon:       '<img src="assets/items/body_reddevil.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_BODY_REDDEVIL,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'armor', img: 'assets/items/body_reddevil.png' },
      armorId:    'body_reddevil',
      armor:      88,
    },
    // ── PPAP ──
    {
      id:         'body_ppap',
      name:       'BODY PPAP',
      icon:       '<img src="assets/items/body_ppap.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_BODY_PPAP,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'armor', img: 'assets/items/body_ppap.png' },
      armorId:    'body_ppap',
      armor:      78,
    },
    // ── BLUE ACT ──
    {
      id:         'body_blueact',
      name:       'BODY BLUE ACT',
      icon:       '<img src="assets/items/body_blueact.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_BODY_BLUEACT,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'armor', img: 'assets/items/body_blueact.png' },
      armorId:    'body_blueact',
      armor:      90,
    },
    // ── CHICAGO ──
    {
      id:         'body_chicago',
      name:       'BODY CHICAGO',
      icon:       '<img src="assets/items/body_chicago.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_BODY_CHICAGO,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'armor', img: 'assets/items/body_chicago.png' },
      armorId:    'body_chicago',
      armor:      86,
    },
    // ── EVIL ──
    {
      id:         'body_evil',
      name:       'BODY EVIL',
      icon:       '<img src="assets/items/body_evil.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_BODY_EVIL,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'armor', img: 'assets/items/body_evil.png' },
      armorId:    'body_evil',
      armor:      82,
    },
    // ── LUCIFER ──
    {
      id:         'body_lucifer',
      name:       'BODY LUCIFER',
      icon:       '<img src="assets/items/body_lucifer.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_BODY_LUCIFER,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'armor', img: 'assets/items/body_lucifer.png' },
      armorId:    'body_lucifer',
      armor:      84,
    },
    // ── PIGGY ──
    {
      id:         'body_piggy',
      name:       'BODY PIGGY',
      icon:       '<img src="assets/items/body_piggy.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_BODY_PIGGY,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'armor', img: 'assets/items/body_piggy.png' },
      armorId:    'body_piggy',
      armor:      80,
    },
  ],
  helmet: [
    // ── RED DEVIL ──
    {
      id:         'head_reddevil',
      name:       'HEAD RED DEVIL',
      icon:       '<img src="assets/items/head_reddevil.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_HEAD_REDDEVIL,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'helmet', img: 'assets/items/head_reddevil.png' },
      armorId:    'head_reddevil',
      armor:      89,
    },
    // ── PPAP ──
    {
      id:         'head_ppap',
      name:       'HEAD PPAP',
      icon:       '<img src="assets/items/head_ppap.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_HEAD_PPAP,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'helmet', img: 'assets/items/head_ppap.png' },
      armorId:    'head_ppap',
      armor:      79,
    },
    // ── BLUE ACT ──
    {
      id:         'head_blueact',
      name:       'HEAD BLUE ACT',
      icon:       '<img src="assets/items/head_blueact.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_HEAD_BLUEACT,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'helmet', img: 'assets/items/head_blueact.png' },
      armorId:    'head_blueact',
      armor:      91,
    },
    // ── CHICAGO ──
    {
      id:         'head_chicago',
      name:       'HEAD CHICAGO',
      icon:       '<img src="assets/items/head_chicago.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_HEAD_CHICAGO,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'helmet', img: 'assets/items/head_chicago.png' },
      armorId:    'head_chicago',
      armor:      87,
    },
    // ── EVIL ──
    {
      id:         'head_evil',
      name:       'HEAD EVIL',
      icon:       '<img src="assets/items/head_evil.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_HEAD_EVIL,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'helmet', img: 'assets/items/head_evil.png' },
      armorId:    'head_evil',
      armor:      83,
    },
    // ── LUCIFER ──
    {
      id:         'head_lucifer',
      name:       'HEAD LUCIFER',
      icon:       '<img src="assets/items/head_lucifer.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_HEAD_LUCIFER,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'helmet', img: 'assets/items/head_lucifer.png' },
      armorId:    'head_lucifer',
      armor:      85,
    },
    // ── PIGGY ──
    {
      id:         'head_piggy',
      name:       'HEAD PIGGY',
      icon:       '<img src="assets/items/head_piggy.png" style="width:56px;height:auto;object-fit:contain;image-rendering:auto;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_HEAD_PIGGY,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'helmet', img: 'assets/items/head_piggy.png' },
      armorId:    'head_piggy',
      armor:      81,
    },
  ],
  med: [
    {
      id:         'bandage',
      name:       'BANDAGE',
      icon:       '<img src="assets/items/bandage.png" style="width:32px;height:auto;object-fit:contain;">',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_BANDAGE ?? 50,
      consumable: true,
      noStackBP:  true,
      equip:      { type: 'med' },
      heal:       100,
    },
  ],
  supply: [
    {
      id:         'ammo_box',
      name:       'AMMO BOX',
      icon:       '📦',
      currency:   'money',
      price:      () => GAME_CONFIG.PRICE_AMMO_BOX,
      consumable: true,
      noStackBP:  false,
      equip:      null,
    },
  ],
};
